// trademark/page.js
import React from 'react';

const TrademarkCopyright = () => {
  return (
    <div className="min-h-screen bg-cover  bg-fixed bg-center bg-pyellow py-10">
      <div className="max-w-4xl mx-auto bg-white p-8 shadow-lg rounded-lg bg-opacity-40">
        <h1 className="text-4xl font-script text-pgreen font-bold mb-8 text-center">
          Trademark & Copyright Policy
        </h1>

        <section className="mb-8">
          <h2 className="text-2xl font-script text-pgreen font-semibold mb-4">Introduction</h2>
          <p>
            Welcome to the Golden Pakkada Intellectual Property Policy. This
            policy outlines the guidelines and principles governing the intellectual
            property rights associated with our brand, content, and assets. By accessing
            and using our website or interacting with our materials, you agree to abide by
            the terms of this policy.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-script text-pgreen font-semibold mb-4">
            Ownership of Intellectual Property
          </h2>
          <h3 className="text-xl font-script text-pgreen font-semibold mb-2">Trademarks:</h3>
          <p className="mb-4">
            All trademarks, service marks, logos, and trade names displayed on our
            website and materials are the property of Golden Pakkada or their
            respective owners. Unauthorized use of these marks is prohibited.
          </p>
          <h3 className="text-xl font-script text-pgreen font-semibold mb-2">Copyright:</h3>
          <p>
            All content available on the website, including text, images, graphics,
            videos, and software, is protected by copyright laws. Unless expressly
            stated otherwise, Golden Pakkada or its content suppliers own the
            copyright to this content.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-script text-pgreen font-semibold mb-4">
            Use of Intellectual Property
          </h2>
          <h3 className="text-xl font-script text-pgreen font-semibold mb-2">Permission:</h3>
          <p className="mb-4">
            Except as expressly permitted by this policy or applicable laws, you may not
            use our trademarks, service marks, logos, or copyrighted materials without our
            prior written consent.
          </p>
          <h3 className="text-xl font-script text-pgreen font-semibold mb-2">Limited License:</h3>
          <p>
            We grant you a limited, non-exclusive, non-transferable, and revocable
            license to access and use our website and materials solely for personal,
            non-commercial purposes.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-script text-pgreen font-semibold mb-4">Prohibited Uses</h2>
          <h3 className="text-xl font-script text-pgreen font-semibold mb-2">Modification:</h3>
          <p className="mb-4">
            You may not modify, alter, or adapt any of our trademarks, logos, or
            copyrighted materials in any way that could be considered misleading or
            infringing.
          </p>
          <h3 className="text-xl font-script text-pgreen font-semibold mb-2">Misrepresentation:</h3>
          <p className="mb-4">
            You may not use our intellectual property in a manner that suggests
            endorsement, affiliation, or sponsorship by Golden Pakkada when no
            such relationship exists.
          </p>
          <h3 className="text-xl font-script text-pgreen font-semibold mb-2">Competitive Use:</h3>
          <p>
            You may not use our intellectual property to compete with Golden Pakkada,
            reproduce our products/services, or create confusion in the marketplace.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-script text-pgreen font-semibold mb-4">Enforcement</h2>
          <h3 className="text-xl font-script text-pgreen font-semibold mb-2">Infringement Reporting:</h3>
          <p>
            If you believe that any content on our website or materials infringes your
            intellectual property rights, please contact us using the provided contact
            information. We will promptly address and investigate such concerns.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-script text-pgreen font-semibold mb-4">Disclaimer</h2>
          <h3 className="text-xl font-script text-pgreen font-semibold mb-2">No Transfer of Rights:</h3>
          <p>
            This policy does not grant you ownership rights to our intellectual property.
            Any goodwill generated by your use of our intellectual property accrues to
            Golden Pakkada.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-script text-pgreen font-semibold mb-4">Updates to Policy</h2>
          <h3 className="text-xl font-script text-pgreen font-semibold mb-2">Policy Changes:</h3>
          <p>
            We reserve the right to modify, update, or replace this Intellectual Property
            Policy at any time without notice. Your continued use of our website and
            materials after such changes constitutes your acceptance of the modified
            policy.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-script text-pgreen font-semibold mb-4">Contact Information</h2>
          <p>
            If you have any questions or concerns regarding this Intellectual Property
            Policy, please contact us through our Contact Us Page.
          </p>
        </section>
      </div>
    </div>
  );
};

export default TrademarkCopyright;
